### ISSUE TITLE
ERC721 error: unexpected null - @openzeppelin/subgraphs/src/fetch/erc721.ts, line 64, column 9

### ISSUE THREAD

**Issue by RyRy79261** [OpenZeppelin/openzeppelin-subgraphs#10]
Due to the `fetchERC721` function having the return statement `null as ERC721Contract`, once deploying the subgraph, the subgraph fails with the following message: [it can be viewed here](https://thegraph.com/studio/subgraph/rinkeby-erc721/)
```
Error: Mapping aborted at node_modules/@openzeppelin/subgraphs/src/fetch/erc721.ts, line 64, column 9, with message: unexpected null wasm backtrace: 0: 0x20c3 - <unknown>!node_modules/@openzeppelin/subgraphs/src/fetch/erc721/fetchERC721 1: 0x2474 - <unknown>!node_modules/@openzeppelin/subgraphs/src/datasources/erc721/handleTransfer in handler `handleTransfer` at block #9000018 (4b7dedc5e85a1ce20f6f33cbba93b272c2464fa481c2cd51998c4127f8bf6cb4)
```

This graph was done very simply with the following configuration: 
v0.0.1:
```
{
  "output": "generated/test.",
  "chain": "rinkeby",
  "datasources": [
    { "module": "erc721" }
  ]
}
```

v0.0.8
```
{
  "output": "generated/test.",
  "chain": "rinkeby",
  "datasources": [
    { "startBlock":  9000000, "module": "erc721" }
  ]
}
```

**Comment by RyRy79261** [comment]
@Amxx

**Comment by Amxx** [comment]
Hello @RyRy79261 

- Your subgraph is not publicly available. when trying to view it on the Subgraph studio I get "You are not authorized to see this"

- It is necessary for to return null if the address fetch is not a valid erc721 contract (particularly because of the ERC20/721 transfer class). This should be filtered by the `handleTransfer` function

- Maybe the recent move to `apiVersion: 0.0.5` has an effect. I'll investigate

**Comment by Amxx** [comment]
Was able to reproduce and fix the issue. 

Changes have been published in version 0.1.5. Could you please try and let me know if that works for you?

**Comment by RyRy79261** [comment]
Amazing, just heading to lunch then will test it out

**Comment by RyRy79261** [comment]
Epic, seems to be running smoothly now, thanks!
