### ISSUE TITLE
Some questions and proposal

### ISSUE THREAD

**Issue by JavierCervilla** [OpenZeppelin/openzeppelin-subgraphs#13]
First of all Happy New Year to all and thanks for this repo, it is helping me to learn a lot, the second thing is that I would like to propose to make a default fetch URI in token creation ERC1155 for those contracts that does not implement the IMETADATAURI Interface because the replacement of the ID is done by the client, on the other hand, I like the system and I have created a fork of this repo because I would like to extend the templates, but I can not make it work, I can not even install the dependencies. Greetings to all and happy 2022.

**Comment by Amxx** [comment]
Hello @JavierCervilla 

I'm not sure I fully understand your question, because it's honestly difficult to read, but here are some elements that might provide an answer.

The ERC1155 subgraph indexing is purely based on [the specification interface](https://eips.ethereum.org/EIPS/eip-1155). The base interface described an URI event, and we are using it to populate this subgraph.

It is true that the standard also includes a `IERC1155MetadataURI` interface, that I've been ignoring so far. I'll definitely add it to the ERC1555 datasource to try and fetch an URI on token creation. This value will be kept, unless overridden by a `URI` event.

Does that sound good to you ?

**Comment by frangio** [comment]
From my reading the specification requires a `URI` event even on token creation, so I don't think it's necessary to add custom handling.

I think OP refers by "replacement of the ID is done by the client" to the feature where the text `{id}` in the returned URI is replaced with the token id. Should the subgraph do this replacement?

**Comment by Amxx** [comment]
its not hard to do it, so why not.

**Comment by Amxx** [comment]
Fixed in #14
