### ISSUE TITLE
Upgrade graph dependencies for performance updates

### ISSUE THREAD

**Issue by imthatcarlos** [OpenZeppelin/openzeppelin-subgraphs#22]
Not an issue, but there was a [new article from edge and node](https://medium.com/edge-node-engineering/two-simple-subgraph-performance-improvements-a76c6b3e7eac) regarding updates to their packages `graph-cli` and `graph-ts` for indexing improvments

- Using immutable entities
- Using Bytes as the id

Would be great if this repo implemented these changes to improve indexing speed. I'll see if I can get around to it this week as we need these improvements for our production subgraph indexing `bsc` contract events (it's painfully slow - see this [recent issue](https://github.com/graphprotocol/graph-node/issues/3470) and [this one](https://github.com/graphprotocol/graph-node/issues/3106))

**Comment by Amxx** [comment]
Thank you @imthatcarlos for this issue.

I'll work on that. 

I'm not sure how much improvement can be achieved, partly because we rely on the fact that some "immutable" entries can be overridden with no changes, so we don't have to do a lookup that would be a point of synchronization. We'll have to benchmark and adapt, so don't expect a fast update, but it's definitely on the roadmap!

**Comment by Amxx** [comment]
If you want to work on that feature, the right place to start might be the amxx/graphprotocol-utils repo. 

I think we can start by making the transaction object immutable, and update the graph compiler to support this new syntax

Then we will be free to work here.

**Comment by imthatcarlos** [comment]
hey @Amxx - thanks for your response. for the project, we decided to move to polygon so indexing should be better there. i'll look into your utils repo !

**Comment by Amxx** [comment]
Should be addressed in #25

**Comment by imthatcarlos** [comment]
legend @Amxx 🙏
